import { defineConfig, globalIgnores } from "eslint/config";
import nextVitals from "eslint-config-next/core-web-vitals";
import nextTs from "eslint-config-next/typescript";

const eslintConfig = defineConfig([
  ...nextVitals,
  ...nextTs,
  // Override default ignores of eslint-config-next.
  globalIgnores([
    // Default ignores of eslint-config-next:
    ".next/**",
    "out/**",
    "build/**",
    "next-env.d.ts",
    // Agent worktrees / local session files.
    ".claude/**",
    ".pglite/**",
    // Generated by the dotmatrix shadcn registry — consumed as-is, not edited.
    "src/lib/dotmatrix-core.tsx",
    "src/lib/dotmatrix-hooks.ts",
    "src/components/ui/dotm-square-*.tsx",
  ]),
  {
    // Generated by the dotmatrix shadcn registry — consumed as-is, not edited.
    files: [
      "src/lib/dotmatrix-core.tsx",
      "src/lib/dotmatrix-hooks.ts",
      "src/components/ui/dotm-*.tsx",
    ],
    rules: {
      "react-hooks/set-state-in-effect": "off",
      "@typescript-eslint/no-unused-vars": "off",
    },
  },
]);

export default eslintConfig;
